package th.com.bloomcode.paymentservice.model.payment.dto;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import th.com.bloomcode.paymentservice.model.BaseModel;

import java.math.BigDecimal;
import java.sql.Timestamp;

@Getter
@Setter
@NoArgsConstructor
public class UnBlockDocument extends BaseModel {

    private String lineInvoiceDocumentNo;
    private String lineCompanyCode;
    private String lineInvoiceFiscalYear;
    private String lineDocumentBaseType;
    private String lineDocumentType;
    private String linePaymentBlock;
    private int countChild;
    private String poDocumentNo;
    private Timestamp reverseDateAcct;
    private String reverseReason;
    private String invoiceDocumentNo;
    private String reverseInvoiceDocumentNo;
    private String headerReference;
    private String headerReference2;
    private String documentHeaderText;
    private String originalDocumentNo;
    private String originalFiscalYear;
    private String reverseOriginalDocumentNo;
    private String reverseOriginalFiscalYear;
    private String costCenter1;
    private String costCenter2;
    private String documentType;
    private String companyCode;
    private Timestamp dateDoc;
    private Timestamp dateAcct;
    private int period;
    private String currency;
    private String originalDocument;
    private Timestamp documentCreated;
    private String userPark;
    private String userPost;
    private String postingKey;
    private String accountType;
    private String drCr;
    private String glAccount;
    private String fiArea;
    private String costCenter;
    private String fundSource;
    private String bgCode;
    private String bgActivity;
    private String costActivity;
    private BigDecimal amount;
    private String reference3;
    private String assignment;
    private String brDocumentNo;
    private String brLine;
    private String paymentCenter;
    private String bankBook;
    private String bankBranchNo;
    private String tradingPartner;
    private String tradingPartnerPark;
    private String specialGL;
    private Timestamp dateBaseLine;
    private Timestamp dateValue;
    private String assetNo;
    private String assetSubNo;
    private BigDecimal qty;
    private String uom;
    private String income;
    private String reference1;
    private String reference2;
    private int poLine;
    private String paymentReference;
    private String subAccount;
    private String subAccountOwner;
    private String depositAccount;
    private String depositAccountOwner;
    private String gpsc;
    private String gpscGroup;
    private String lineItemText;
    private String lineDesc;
    private String paymentTerm;
    private String paymentMethod;
    private String wtxType;
    private String wtxCode;
    private BigDecimal wtxBase;
    private BigDecimal wtxAmount;
    private String wtxTypeP;
    private String wtxCodeP;
    private BigDecimal wtxBaseP;
    private BigDecimal wtxAmountP;
    private String payee;
    private String payeeTaxId;
    private String vendorCode;
    private String vendorName;
    private String vendorTaxId;
    private String bankAccountNo;
    private String bankAccountHolderName;
    private String paymentBlock;
    private boolean confirmVendor;
    private String fundType;
    private String documentBaseType;
    private String selectGroupDocument;
    private Long paymentId;
    private String paymentName;
    private Timestamp paymentDate;
    private String proposalStatus;
    private String runStatus;


    public static final String COLUMN_NAME_GL_HEAD_ID = "ID";
    public static final String COLUMN_NAME_LINE_COMPANY_CODE = "LINE_COMPANY_CODE";
    public static final String COLUMN_NAME_LINE_INVOICE_DOCUMENT_NO = "LINE_INVOICE_DOCUMENT_NO";
    public static final String COLUMN_NAME_LINE_INVOICE_FISCAL_YEAR = "LINE_INVOICE_FISCAL_YEAR";
    public static final String COLUMN_NAME_LINE_DOCUMENT_BASE_TYPE = "LINE_DOCUMENT_BASE_TYPE";
    public static final String COLUMN_NAME_LINE_DOCUMENT_TYPE = "LINE_DOCUMENT_TYPE";
    public static final String COLUMN_NAME_LINE_PAYMENT_BLOCK = "LINE_PAYMENT_BLOCK";

    public static final String COLUMN_NAME_COUNT_CHILD = "COUNT_CHILD";
    public static final String COLUMN_NAME_PO_DOCUMENT_NO = "PO_DOCUMENT_NO";
    public static final String COLUMN_NAME_REVERSE_DATE_ACCT = "REVERSE_DATE_ACCT";
    public static final String COLUMN_NAME_REVERSE_REASON = "REVERSE_REASON";
    public static final String COLUMN_NAME_INVOICE_DOCUMENT_NO = "INVOICE_DOCUMENT_NO";
    public static final String COLUMN_NAME_REVERSE_INVOICE_DOCUMENT_NO = "REVERSE_INVOICE_DOCUMENT_NO";
    public static final String COLUMN_NAME_HEADER_REFERENCE = "HEADER_REFERENCE";
    public static final String COLUMN_NAME_HEADER_REFERENCE2 = "HEADER_REFERENCE2";
    public static final String COLUMN_NAME_DOCUMENT_HEADER_TEXT = "DOCUMENT_HEADER_TEXT";
    public static final String COLUMN_NAME_ORIGINAL_DOCUMENT_NO = "ORIGINAL_DOCUMENT_NO";
    public static final String COLUMN_NAME_ORIGINAL_FISCAL_YEAR = "ORIGINAL_FISCAL_YEAR";
    public static final String COLUMN_NAME_REVERSE_ORIGINAL_DOCUMENT_NO = "REVERSE_ORIGINAL_DOCUMENT_NO";
    public static final String COLUMN_NAME_REVERSE_ORIGINAL_FISCAL_YEAR = "REVERSE_ORIGINAL_FISCAL_YEAR";
    public static final String COLUMN_NAME_COST_CENTER1 = "COST_CENTER1";
    public static final String COLUMN_NAME_COST_CENTER2 = "COST_CENTER2";
    public static final String COLUMN_NAME_DOCUMENT_TYPE = "DOCUMENT_TYPE";
    public static final String COLUMN_NAME_COMPANY_CODE = "COMPANY_CODE";
    public static final String COLUMN_NAME_DATE_DOC = "DATE_DOC";
    public static final String COLUMN_NAME_DATE_ACCT = "DATE_ACCT";
    public static final String COLUMN_NAME_PERIOD = "PERIOD";
    public static final String COLUMN_NAME_CURRENCY = "CURRENCY";
    public static final String COLUMN_NAME_ORIGINAL_DOCUMENT = "ORIGINAL_DOCUMENT";
    public static final String COLUMN_NAME_DOCUMENT_CREATED = "DOCUMENT_CREATED";
    public static final String COLUMN_NAME_USER_PARK = "USER_PARK";
    public static final String COLUMN_NAME_USER_POST = "USER_POST";
    public static final String COLUMN_NAME_POSTING_KEY = "POSTING_KEY";
    public static final String COLUMN_NAME_ACCOUNT_TYPE = "ACCOUNT_TYPE";
    public static final String COLUMN_NAME_DR_CR = "DR_CR";
    public static final String COLUMN_NAME_GL_ACCOUNT = "GL_ACCOUNT";
    public static final String COLUMN_NAME_FI_AREA = "FI_AREA";
    public static final String COLUMN_NAME_COST_CENTER = "COST_CENTER";
    public static final String COLUMN_NAME_FUND_SOURCE = "FUND_SOURCE";
    public static final String COLUMN_NAME_BG_CODE = "BG_CODE";
    public static final String COLUMN_NAME_BG_ACTIVITY = "BG_ACTIVITY";
    public static final String COLUMN_NAME_COST_ACTIVITY = "COST_ACTIVITY";
    public static final String COLUMN_NAME_AMOUNT = "AMOUNT";
    public static final String COLUMN_NAME_REFERENCE3 = "REFERENCE3";
    public static final String COLUMN_NAME_ASSIGNMENT = "ASSIGNMENT";
    public static final String COLUMN_NAME_BR_DOCUMENT_NO = "BR_DOCUMENT_NO";
    public static final String COLUMN_NAME_BR_LINE = "BR_LINE";
    public static final String COLUMN_NAME_PAYMENT_CENTER = "PAYMENT_CENTER";
    public static final String COLUMN_NAME_BANK_BOOK = "BANK_BOOK";
    public static final String COLUMN_NAME_BANK_BRANCH_NO = "BANK_BRANCH_NO";
    public static final String COLUMN_NAME_TRADING_PARTNER = "TRADING_PARTNER";
    public static final String COLUMN_NAME_TRADING_PARTNER_PARK = "TRADING_PARTNER_PARK";
    public static final String COLUMN_NAME_SPECIAL_GL = "SPECIAL_GL";
    public static final String COLUMN_NAME_DATE_BASE_LINE = "DATE_BASE_LINE";
    public static final String COLUMN_NAME_DATE_VALUE = "DATE_VALUE";
    public static final String COLUMN_NAME_ASSET_NO = "ASSET_NO";
    public static final String COLUMN_NAME_ASSET_SUB_NO = "ASSET_SUB_NO";
    public static final String COLUMN_NAME_QTY = "QTY";
    public static final String COLUMN_NAME_UOM = "UOM";
    public static final String COLUMN_NAME_INCOME = "INCOME";
    public static final String COLUMN_NAME_REFERENCE1 = "REFERENCE1";
    public static final String COLUMN_NAME_REFERENCE2 = "REFERENCE2";
    public static final String COLUMN_NAME_PO_LINE = "PO_LINE";
    public static final String COLUMN_NAME_PAYMENT_REFERENCE = "PAYMENT_REFERENCE";
    public static final String COLUMN_NAME_SUB_ACCOUNT = "SUB_ACCOUNT";
    public static final String COLUMN_NAME_SUB_ACCOUNT_OWNER = "SUB_ACCOUNT_OWNER";
    public static final String COLUMN_NAME_DEPOSIT_ACCOUNT = "DEPOSIT_ACCOUNT";
    public static final String COLUMN_NAME_DEPOSIT_ACCOUNT_OWNER = "DEPOSIT_ACCOUNT_OWNER";
    public static final String COLUMN_NAME_GPSC = "GPSC";
    public static final String COLUMN_NAME_GPSC_GROUP = "GPSC_GROUP";
    public static final String COLUMN_NAME_LINE_ITEM_TEXT = "LINE_ITEM_TEXT";
    public static final String COLUMN_NAME_LINE_DESC = "LINE_DESC";
    public static final String COLUMN_NAME_PAYMENT_TERM = "PAYMENT_TERM";
    public static final String COLUMN_NAME_PAYMENT_METHOD = "PAYMENT_METHOD";
    public static final String COLUMN_NAME_WTX_TYPE = "WTX_TYPE";
    public static final String COLUMN_NAME_WTX_CODE = "WTX_CODE";
    public static final String COLUMN_NAME_WTX_BASE = "WTX_BASE";
    public static final String COLUMN_NAME_WTX_AMOUNT = "WTX_AMOUNT";
    public static final String COLUMN_NAME_WTX_TYPE_P = "WTX_TYPE_P";
    public static final String COLUMN_NAME_WTX_CODE_P = "WTX_CODE_P";
    public static final String COLUMN_NAME_WTX_BASE_P = "WTX_BASE_P";
    public static final String COLUMN_NAME_WTX_AMOUNT_P = "WTX_AMOUNT_P";
    public static final String COLUMN_NAME_PAYEE = "PAYEE";
    public static final String COLUMN_NAME_PAYEE_TAX_ID = "PAYEE_TAX_ID";
    public static final String COLUMN_NAME_VENDOR = "VENDOR";
    public static final String COLUMN_NAME_VENDOR_NAME = "VENDOR_NAME";
    public static final String COLUMN_NAME_VENDOR_TAX_ID = "VENDOR_TAX_ID";
    public static final String COLUMN_NAME_BANK_ACCOUNT_NO = "BANK_ACCOUNT_NO";
    public static final String COLUMN_NAME_BANK_ACCOUNT_HOLDER_NAME = "BANK_ACCOUNT_HOLDER_NAME";
    public static final String COLUMN_NAME_PAYMENT_BLOCK = "PAYMENT_BLOCK";
    public static final String COLUMN_NAME_CONFIRM_VENDOR = "CONFIRM_VENDOR";
    public static final String COLUMN_NAME_FUND_TYPE = "FUND_TYPE";
    public static final String COLUMN_NAME_DOCUMENT_BASE_TYPE = "DOCUMENT_BASE_TYPE";
    public static final String COLUMN_NAME_SELECT_GROUP_DOCUMENT = "SELECT_GROUP_DOCUMENT";

    public static final String COLUMN_NAME_PAYMENT_ID = "PAYMENT_ID";
    public static final String COLUMN_NAME_PAYMENT_NAME = "PAYMENT_NAME";
    public static final String COLUMN_NAME_PAYMENT_DATE = "PAYMENT_DATE";
    public static final String COLUMN_NAME_PROPOSAL_STATUS = "PROPOSAL_STATUS";
    public static final String COLUMN_NAME_RUN_STATUS = "RUN_STATUS";



    public UnBlockDocument(Long id, String lineInvoiceDocumentNo, String lineCompanyCode, String lineInvoiceFiscalYear, String lineDocumentBaseType, String lineDocumentType,String linePaymentBlock, int countChild, String poDocumentNo, Timestamp reverseDateAcct, String reverseReason, String invoiceDocumentNo, String reverseInvoiceDocumentNo, String headerReference, String headerReference2, String documentHeaderText, String originalDocumentNo, String originalFiscalYear, String reverseOriginalDocumentNo, String reverseOriginalFiscalYear, String costCenter1, String costCenter2, String documentType, String companyCode, Timestamp dateDoc, Timestamp dateAcct, int period, String currency, String originalDocument, Timestamp documentCreated, String userPark, String userPost, String postingKey, String accountType, String drCr, String glAccount, String fiArea, String costCenter, String fundSource, String bgCode, String bgActivity, String costActivity, BigDecimal amount, String reference3, String assignment, String brDocumentNo, String brLine, String paymentCenter, String bankBook, String bankBranchNo, String tradingPartner, String tradingPartnerPark, String specialGL, Timestamp dateBaseLine, Timestamp dateValue, String assetNo, String assetSubNo, BigDecimal qty, String uom, String income, String reference1, String reference2, int poLine, String paymentReference, String subAccount, String subAccountOwner, String depositAccount, String depositAccountOwner, String gpsc, String gpscGroup, String lineItemText, String lineDesc, String paymentTerm, String paymentMethod, String wtxType, String wtxCode, BigDecimal wtxBase, BigDecimal wtxAmount, String wtxTypeP, String wtxCodeP, BigDecimal wtxBaseP, BigDecimal wtxAmountP, String payee, String payeeTaxId, String vendor, String vendorName, String vendorTaxId, String bankAccountNo, String bankAccountHolderName, String paymentBlock, boolean confirmVendor, String fundType, String documentBaseType, String selectGroupDocument
     ,Long paymentId
      , String paymentName,
               Timestamp paymentDate,
               String proposalStatus,
                           String runStatus) {
        super(id);
        this.lineInvoiceDocumentNo = lineInvoiceDocumentNo;
        this.lineCompanyCode = lineCompanyCode;
        this.lineInvoiceFiscalYear = lineInvoiceFiscalYear;
        this.lineDocumentBaseType = lineDocumentBaseType;
        this.lineDocumentType = lineDocumentType;
        this.linePaymentBlock = linePaymentBlock;
        this.countChild = countChild;
        this.poDocumentNo = poDocumentNo;
        this.reverseDateAcct = reverseDateAcct;
        this.reverseReason = reverseReason;
        this.invoiceDocumentNo = invoiceDocumentNo;
        this.reverseInvoiceDocumentNo = reverseInvoiceDocumentNo;
        this.headerReference = headerReference;
        this.headerReference2 = headerReference2;
        this.documentHeaderText = documentHeaderText;
        this.originalDocumentNo = originalDocumentNo;
        this.originalFiscalYear = originalFiscalYear;
        this.reverseOriginalDocumentNo = reverseOriginalDocumentNo;
        this.reverseOriginalFiscalYear = reverseOriginalFiscalYear;
        this.costCenter1 = costCenter1;
        this.costCenter2 = costCenter2;
        this.documentType = documentType;
        this.companyCode = companyCode;
        this.dateDoc = dateDoc;
        this.dateAcct = dateAcct;
        this.period = period;
        this.currency = currency;
        this.originalDocument = originalDocument;
        this.documentCreated = documentCreated;
        this.userPark = userPark;
        this.userPost = userPost;
        this.postingKey = postingKey;
        this.accountType = accountType;
        this.drCr = drCr;
        this.glAccount = glAccount;
        this.fiArea = fiArea;
        this.costCenter = costCenter;
        this.fundSource = fundSource;
        this.bgCode = bgCode;
        this.bgActivity = bgActivity;
        this.costActivity = costActivity;
        this.amount = amount;
        this.reference3 = reference3;
        this.assignment = assignment;
        this.brDocumentNo = brDocumentNo;
        this.brLine = brLine;
        this.paymentCenter = paymentCenter;
        this.bankBook = bankBook;
        this.bankBranchNo = bankBranchNo;
        this.tradingPartner = tradingPartner;
        this.tradingPartnerPark = tradingPartnerPark;
        this.specialGL = specialGL;
        this.dateBaseLine = dateBaseLine;
        this.dateValue = dateValue;
        this.assetNo = assetNo;
        this.assetSubNo = assetSubNo;
        this.qty = qty;
        this.uom = uom;
        this.income = income;
        this.reference1 = reference1;
        this.reference2 = reference2;
        this.poLine = poLine;
        this.paymentReference = paymentReference;
        this.subAccount = subAccount;
        this.subAccountOwner = subAccountOwner;
        this.depositAccount = depositAccount;
        this.depositAccountOwner = depositAccountOwner;
        this.gpsc = gpsc;
        this.gpscGroup = gpscGroup;
        this.lineItemText = lineItemText;
        this.lineDesc = lineDesc;
        this.paymentTerm = paymentTerm;
        this.paymentMethod = paymentMethod;
        this.wtxType = wtxType;
        this.wtxCode = wtxCode;
        this.wtxBase = wtxBase;
        this.wtxAmount = wtxAmount;
        this.wtxTypeP = wtxTypeP;
        this.wtxCodeP = wtxCodeP;
        this.wtxBaseP = wtxBaseP;
        this.wtxAmountP = wtxAmountP;
        this.payee = payee;
        this.payeeTaxId = payeeTaxId;
        this.vendorCode = vendor;
        this.vendorName = vendorName;
        this.vendorTaxId = vendorTaxId;
        this.bankAccountNo = bankAccountNo;
        this.bankAccountHolderName = bankAccountHolderName;
        this.paymentBlock = paymentBlock;
        this.confirmVendor = confirmVendor;
        this.fundType = fundType;
        this.documentBaseType = documentBaseType;
        this.selectGroupDocument = selectGroupDocument;
        this.paymentId=paymentId;
        this.paymentName = paymentName;
        this.paymentDate = paymentDate;
        this.proposalStatus = proposalStatus;
        this.runStatus = runStatus;


    }
}
